### ISSUE TITLE
审批王修改工作区（有同名工作区）拥有者和管理员时，修改后系统提示不能有同名工作区，这时工作区的管理员会自动变成两个相同的人员

### ISSUE THREAD

**Issue by chenzhipei** [steedos/workflow#10]
![2015-12-07 8 53 08](https://cloud.githubusercontent.com/assets/15027092/11645327/9c103a56-9d8e-11e5-9ea1-df2fcdd60068.png)

**Comment by steedos** [comment]
待新版本解决
