### ISSUE TITLE
接入企业微信成为第三方应用

### ISSUE THREAD

**Issue by steedos** [steedos/workflow#1389]
管理后台：https://open.work.weixin.qq.com/
开发API：https://work.weixin.qq.com/api/doc
操作：
- 在apps中开发企业微信包（steedos-connect-qiyeweixin）

1. - [ ] 服务商注册应用，创建应用套件。创建套件过程中，需要调用系统事件接收URL接口，系统将会把此套件的授权变更事件以及ticket参数推送给此URL，ticket说明详见API接口说明。https://work.weixin.qq.com/api/doc#10514
2. - [ ] 系统事件接收URL接口的主要功能，接受消息配置。企业微信将发送GET请求到填写的URL上，GET请求携带四个参数，企业在获取时需要做Urldecode处理，否则会验证不成功。验证过程中，审批王apps应用需要对企业微信传递来的数据使用微信提供的库进行解密处理，目前提供的有c++/python/php/java/c#等语言版本，咨询客服无js版本。https://work.weixin.qq.com/api/doc#10127
加密解密库：https://github.com/node-webot/wechat-crypto
3. - [ ] 企业授权应用，加入某企业授权使用后，企业微信发送临时授权码给审批王apps应用，apps需要使用临时授权码调用企业微信的api获取永久授权码和授权信息，该永久授权码用于以后的调用企业微信api。https://work.weixin.qq.com/api/doc#10974
4. - [ ] 审批王apps应用使用企业微信接口发消息、管理通讯录等。假设某企业授权使用审批王apps应用后，可以获取该企业的access_token，调用企业微信相关的API进行发消息、管理通讯录和应用等操作。
https://work.weixin.qq.com/api/doc#10975
5. - [ ] 回调协议，通讯录变更，ticket变更等，企业微信会调用任务2的URL发送推送消息。对推送消息进行处理。https://work.weixin.qq.com/api/doc#10982 
6. - [ ] 单点登录：https://work.weixin.qq.com/api/doc#10991

- 认证企业微信，发布企业应用

**Comment by liminglang** [comment]
企业微信已经介入的审批软件有几家了，如果审批王接入企业微信，那么如何突出审批王，我们的特色功能是什么？
