### ISSUE TITLE
QHD：修改发文脚本，调整文件编号、签发日期

### ISSUE THREAD

**Issue by marchtian** [steedos/workflow#1988]
集团/股份发文，文件编号、签发日期不准确，希望是在 文书编号 到 打字室排版时 再生成
关于文件编号，拟作如下调整：
（1）修改 文件编号 非必填
（2）增加脚本，“文书编号”这一步选择下一步为“打字室排版”、并点发送时，判断，如果文件编号没有填，则不让发送、并弹出提示框，要求填写编号。
（3）去掉 文件编号的默认值，改为由脚本控制，在“文书编号”这一步出现一个“编号”的按钮，点击则自动给 文件编号 字段赋值。
关于签发日期，拟作如下调整：
（1）修改 签发日期 非必填；
（2）去掉 签发日期的默认值；
（3）增加脚本，“文书编号”这一步，依据主要领导、分管领导、主任分签的次序赋值签发日期。

**Comment by baozhoutao** [comment]
[集团or股份发文-文件编号.zip](https://github.com/steedos/apps/files/3078977/or.-.zip)

**Comment by marchtian** [comment]
测试环境测试：股份发文
- [ ] （1）修改 文件编号 为非必填、无默认值
- [ ] （2）修改 签发日期 为非必填、无默认值；
- [ ] （3）增加脚本，“文书编号”这一步选择下一步为“打字室排版”、并点发送时，判断，如果文件编号没有填，则不让发送、并弹出提示框，要求填写编号。function checkFileNo()
- [ ] （4）去掉 文件编号的默认值，改为由脚本控制，在“文书编号”这一步出现一个“编号”的按钮，点击则自动给 文件编号 字段赋值。function addFileNoButton()
- [ ] （5）增加脚本，“文书编号”这一步，依据主要领导、分管领导、主任分签的次序赋值签发日期。function resetFileDate()

**Comment by marchtian** [comment]
集办文书测试后提出，点击“编号”后不但赋值编号、同时赋值签发日期

**Comment by marchtian** [comment]
正式环境修改：股份发文
- [x] （1）修改 文件编号 为非必填、无默认值
- [x] （2）修改 签发日期 为非必填、无默认值；
- [x] （3）增加脚本，“文书编号”这一步选择下一步为“打字室排版”、并点发送时，判断，如果文件编号没有填，则不让发送、并弹出提示框，要求填写编号。function checkFileNo()
- [x] （4）增加脚本控制，在“文书编号”这一步出现一个“编号”的按钮，点击则自动给 文件编号 字段赋值。function addFileNoButton()
- [x] （5）增加脚本，“文书编号”这一步，依据主要领导、分管领导、主任分签的次序赋值签发日期。function resetFileDate()

测试环境测试：集团发文
- [x] （1）修改 文件编号 为非必填、无默认值
- [x] （2）修改 签发日期 为非必填、无默认值；
- [x] （3）增加脚本，“文书编号”这一步选择下一步为“打字室排版”、并点发送时，判断，如果文件编号没有填，则不让发送、并弹出提示框，要求填写编号。function checkFileNo()
- [x] （4）增加脚本控制，在“文书编号”这一步出现一个“编号”的按钮，点击则自动给 文件编号 字段赋值。function addFileNoButton()
- [x] （5）增加脚本，“文书编号”这一步，依据主要领导、分管领导、主任分签的次序赋值签发日期。function resetFileDate()

**Comment by marchtian** [comment]
修改股份发文脚本、股份发文脚本
function checkFileNo(e){
    var nextStep = WorkflowManager.getInstanceStep($("[name=instance_suggestion_next_step]:checked").val())
    if(nextStep && nextStep.name === '打字室排版'){
        if($("[name='文件编号']", $("#instanceform")).val()==""){
            toastr.warning('请填写文件编号，否则无法发给打字室排版。');
            e.preventDefault();
        }
        if($("[name='文件日期']", $("#instanceform")).val()==""){
            toastr.warning('请填写签发日期，否则无法发给打字室排版。');
            e.preventDefault();
        }
    }
}
待继续观察
