### ISSUE TITLE
审批王前台支持按 流程分类 过滤

### ISSUE THREAD

**Issue by baozhoutao** [steedos/workflow#2015]
- [x] instance 记录添加 流程分类字段 category， 并添加索引 孙
- [x] instance 旧数据需要升级 孙
- [x] instance 的category 值处理，值来自 新增，转发，分发
- [x] 服务端添加接口(`/api/workflow/open/pending?workflow_categories=id1,id2`)，支持按流程分类获取待办 孙

- [x] client 新增session  key： workflow_categories
- [x] 流程分类 添加app 字段 包
- [x] 申请单列表支持按 流程分类过滤 包
- [x] 填单，流程列表选择需要 支持按 流程分类显示 包

- [x] 抚顺门户调整
1. - [x] 去掉header上的待审核提醒 陈
2. - [x] 抚顺门户调整 按app 拆分待办列表：通过 服务端按流程分类获取待办接口获取数据 陈

- 审批中心 右边添加 选择流程分类功能，选择流程分类，需要自动切换header上选中的应用。（暂不处理）

**Comment by sunhaolin** [comment]
instance 旧数据增加category字段
```js
db.forms.find({}).forEach(function (form) {
    if (form.category) {
        db.instances.update({
            form: form._id,
            category: {
                $exists: false
            }
        }, {
            $set: {
                category: form.category
            }
        }, {
            $multi: true
        })
    }
})
```
