### ISSUE TITLE
PDRQ-公司信息发布流程的待办需要首页“公司信息”中显示，具体位置见图

### ISSUE THREAD

**Issue by huangyiirene** [steedos/workflow#2043]
![浦东首页](https://user-images.githubusercontent.com/7665279/63479898-88d6f880-c4c2-11e9-96f3-968435088f7d.jpg)
![浦东流程](https://user-images.githubusercontent.com/7665279/63479904-8bd1e900-c4c2-11e9-911a-57bd3abaf1b5.jpg)

**Comment by baozhoutao** [comment]
更新文件：
webapps\hotoa\modules\portal\index.jsp
webapps\hotoa\modules\portal\plugin\workflow_gsxx_pending.jsp
配置环境变量：
`steedos.workflow.gsxx.workflow_categories` 值为 公司信息发布所在的流程分类Id
