### ISSUE TITLE
qhd: 传阅的申请单提交后还会出现在首页待办中，点击首页待办进去没有这个文

### ISSUE THREAD

**Issue by chenzhipei** [steedos/workflow#2049]
steedos_keyvalue表中有一条异常数据：
{
    "_id" : "zQATR35K2XtZyCBKR",
    "user" : "GsZDMQmPQkMxCY2fW",
    "space" : null,
    "key" : "badge",
    "value" : {
        "workflow" : 1
    }
}

**Comment by sunhaolin** [comment]
#2023
