### ISSUE TITLE
集团发文，文书修改编号后直接点发送，则修改的编号未生效

### ISSUE THREAD

**Issue by marchtian** [steedos/workflow#2052]
WHN反映,，关于集团公司发文流程，到了 文书编号这一步
（1）修改掉发文号
![image](https://user-images.githubusercontent.com/7553007/64674407-5c037900-d4a3-11e9-824b-df1a71376129.png)

原本为 65号，修改为650号
（2）直接点“发送”，则 表单山过的 文号 仍然为 65号

因为文书编号这一步 除了 修改文号、没有其他权限。所以，除非 手动点下“保存”，否则直接发送 就会导致 文号不对。
最近她才发现这个问题，所以，之前的很多文号 已然 不对了。这次特提出，强烈要求改进。

**Comment by baozhoutao** [comment]
申请单提交到下一步时，所有修改的字段值都不能保存
