### ISSUE TITLE
PDRQ-附件上传限制

### ISSUE THREAD

**Issue by huangyiirene** [steedos/workflow#2053]
办公自动化系统下所有模块中，后缀为EXE、BAT及COM的附件禁止上传。具体涉及的模块包括：

- [x] 公告通知
- [x] 工作流
- [ ] 新版审批中心: 限制附件上传类型可以做成settings，应该是在上传接口中控制
- [x] 电子邮件
- [x] 文档管理
- [x] 合同管理

**Comment by baozhoutao** [comment]
更改文件：
1 webapps\hotoa\elements\scripts\check_attach.js
2 webapps\hotoa\elements\scripts\jquery-1.11.1.min.js  
3 webapps\hotoa\ui\standard\dialog.htm

**Comment by huangyiirene** [comment]
老平台的部分已更新到生产平台
