### ISSUE TITLE
支持新版华信桌面客户端

### ISSUE THREAD

**Issue by hotlong** [steedos/workflow#2078]

**Comment by yinlianghui** [comment]
- win10/mac上华信客户端、chrome都测试通过
- 目前存在问题：
- [ ] win10审批王客户端，待确认是否支持（因为跑不起来会报错了）
- [ ] IE11、Edge等其他客户端测试确认

**Comment by yinlianghui** [comment]
IE11单独报任务了[IE11不支持push.js推送 #1488](https://github.com/steedos/creator/issues/1488)
