### ISSUE TITLE
CN上转发不成功，没有生成新的文件，控制台没报错，就是出了一个红条框

### ISSUE THREAD

**Issue by huangyiirene** [steedos/workflow#2085]
https://cn.steedos.com/workflow/space/51ae9b1a8e296a29c9000001/completed/aFQ66dCb5KBPzSstp

**Comment by sunhaolin** [comment]
错误的表单标题脚本导致：`{客户}_{项目}` ，应该为`{客户} + '_' + {项目}`
代码提示报错信息已优化
