### ISSUE TITLE
选人控件，“清空”按钮在草稿箱有效、在待办箱里点击无效

### ISSUE THREAD

**Issue by marchtian** [steedos/workflow#2098]
![image](https://user-images.githubusercontent.com/7553007/72713042-461b6880-3ba7-11ea-95ec-d9f13b9912c3.png)
在待办箱里点击“清空”按钮后，再点“保存”，可见选的人还在表单上。
测试流程：cn上的“测试流程”

**Comment by marchtian** [comment]
在saas平台测试，也有同样的问题

**Comment by sunhaolin** [comment]
- [ ] qhd分支
- [ ] dev分支
- [ ] creator
