### ISSUE TITLE
审批王待审核计数不对

### ISSUE THREAD

**Issue by chenzhipei** [steedos/workflow#2099]
![image](https://user-images.githubusercontent.com/15027092/72786159-dae59b00-3c67-11ea-9f90-7aba1c2151f9.png)

**Comment by sunhaolin** [comment]
经测试，目前的saas平台如果收到过待审批文件则计数正常

**Comment by sunhaolin** [comment]
可能是遗留问题，在saas平台修正了

**Comment by sunhaolin** [comment]
注销登录之后还是有问题

**Comment by sunhaolin** [comment]
取消申请操作导致
