### ISSUE TITLE
系统设置里，增加用户（无审批王账号）后，未收到邀请邮件

### ISSUE THREAD

**Issue by marchtian** [steedos/workflow#2104]

**Comment by yinlianghui** [comment]
审批王不再处理类似问题，迁移到二合一版本了，见任务：[SAAS 版本添加用户时如果邮件地址已注册，自动发送确认邮件到用户邮箱中。用户点击确认链接，才正式加入此工作区 #41](https://github.com/steedos/steedos-accounts/issues/41)
