### ISSUE TITLE
表单既在“待审核”中，又在“已审核”中时，选中这张表单，切换tag时，页面没有切换。

### ISSUE THREAD

**Issue by chenzhipei** [steedos/workflow#34]
![2016-01-22 14 08 47](https://cloud.githubusercontent.com/assets/15027092/12503887/8263c5f2-c113-11e5-855e-0cbbb02d2421.png)
![2016-01-22 14 08 55](https://cloud.githubusercontent.com/assets/15027092/12503910/aa85e5e2-c113-11e5-96c0-27e5ee403ce2.png)

**Comment by steedos** [comment]
待新版本处理
