### ISSUE TITLE
审批王受邀请用户完成注册信息后，点击“登录”，进入的是华炎云的官网，没有进华炎云系统

### ISSUE THREAD

**Issue by chenzhipei** [steedos/workflow#4]
![2015-11-30 10 15 55](https://cloud.githubusercontent.com/assets/15027092/11462189/ccce9fbe-974b-11e5-8ff1-6d0ba26ccfe9.png)

**Comment by sunhaolin** [comment]
原逻辑就是这样，setup代码 点击登录指向的是@www_server，如：https://beta.steedos.com:443，故暂不修改

**Comment by marchtian** [comment]
暂不修改
