### ISSUE TITLE
审批王设计表单时，双击选中标题名称或者表单描述时，鼠标往下滚动，内容也会跟着滚动

### ISSUE THREAD

**Issue by chenzhipei** [steedos/workflow#5]
![2015-11-30 11 26 19](https://cloud.githubusercontent.com/assets/15027092/11463020/45baec1a-9757-11e5-999e-8aeb43026b78.png)
![2015-11-30 11 26 39](https://cloud.githubusercontent.com/assets/15027092/11463024/4ad247de-9757-11e5-9c58-a55662e3bc8a.png)
![2015-11-30 11 27 15](https://cloud.githubusercontent.com/assets/15027092/11463025/4eafbbca-9757-11e5-9d1c-1e65595e685e.png)

**Comment by steedos** [comment]
暂不处理
