### ISSUE TITLE
safari浏览器、beta 上选择私有云服务器，连接“192.168.0.23”服务器，登录账户后刷新页面，又要重新登录，登录后点击审批王时报错。

### ISSUE THREAD

**Issue by chenzhipei** [steedos/workflow#53]
![2016-02-23 15 57 40](https://cloud.githubusercontent.com/assets/15027092/13245356/8ecf71f4-da47-11e5-8ec0-f6f08e969739.png)

**Comment by steedos** [comment]
无法重现
